{
    'name' : 'AMCE',
    'description': 'Gestion de Guardias',
    'autor': 'ANAC SOFT',
    'depends': ['base', 'mail', 'asw_framework'],
    'data' : [
        'security/permisos.xml',
        'wizzard/inicio_guardia.xml',
        'wizzard/fin_guardia.xml',        
        'wizzard/configuracion.xml',
        'wizzard/deshabilitacion.xml',
        'wizzard/envio_masivo.xml',
        'wizzard/liquidaciones_report.xml',
        'view/res_company.xml',
        'view/guardia.xml',
        'view/turno_fabrica.xml',
        'view/precio_categoria.xml',
        'view/liquidacion.xml',
        'view/actualizacion_precio.xml',
        'view/proceso_liquidacion.xml',
        'view/presentismo.xml',
        'view/linea_presentismo.xml',
        'view/profesional_concepto.xml',        
        'view/periodo.xml',
        'view/grupo.xml',
        'view/Profesionales.xml',
        'view/categoria.xml',
        'view/turno.xml',
        'view/fabrica.xml',
        'view/concepto.xml',
        'view/linea_turno_fabrica.xml',
        'view/calculo_sac.xml',
        'view/linea_actualizacion.xml',
        'view/anio.xml',
        'view/correcciones_admin.xml',
        'view/email_template_liquidacion.xml',
        'security/ir.model.access.csv',
        'reports/template_liquidacion_listado.xml',
        'reports/template_liquidacion.xml',
        'reports/report_liquidaciones_listado.xml',
        'reports/report_liquidacion.xml',
        'view/reporte_guardias_fabrica.xml',
        'view/menu.xml',
    ],
    'application': True,
}