from . import historia_signos_vitales
from . import historia_score_glasgow
from . import historia_trauma_detalle
from . import opcion_dobe
from . import historia_paciente
from . import plan
from . import mla
from . import paciente
from . import mco
from . import antecedente
from . import signos
from . import score
from . import piel_mucosa
from . import edema
from . import neuro
from . import ap_respiratorio
from . import cyc
from . import cardio
from . import abdomen
from . import urogen
from . import gco
from . import psi
from . import trauma, trauma_lugar, trauma_tipo
from . import mec
from . import diagnos
from . import des
from . import evol
from . import al_llegar
from . import clas_llam
from . import hosp
from . import medicacion
from . import medicamentos
from . import historia
from . import quem
from . import quem
from . import movil
from . import cobertura
from . import estado_mental
from . import cardio_pulso
from . import cardio_soplo
from . import profesional
from . import usuario_app
from . import instituciones