from . import calcula_periodo
from . import calcula_cant_horas
from . import categoria
from . import concepto
from . import guardia
from . import fabrica
from . import turno
from . import precio_categoria
from . import concepto
from . import linea_liquidacion
from . import liquidacion
from . import profesional_concepto
from . import linea_presentismo
from . import presentismo
from . import actualizacion_precio
from . import linea_actualizacion
from . import periodo
from . import anio
from . import Profesionales
from . import grupo
from . import turno_fabrica
from . import linea_turno_fabrica
from . import proceso_liquidacion
from . import calculo_sac
from . import correcciones_admin
from . import res_company
from . import reporte_guardias_fabrica